apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fidelia-app-secrets
  namespace: fidelia
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: fidelia-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: fidelia/database/url
    - secretKey: FIDELIA_SECRET_KEY
      remoteRef:
        key: fidelia/jwt/secret
    - secretKey: MOBILE_MONEY_SECRETS
      remoteRef:
        key: fidelia/mobile_money/secret
    - secretKey: CELERY_BROKER_URL
      remoteRef:
        key: fidelia/celery/broker_url
