apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: djassa-app-secrets
  namespace: djassa
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: djassa-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: djassa/database/url
    - secretKey: DJASSA_SECRET_KEY
      remoteRef:
        key: djassa/jwt/secret
    - secretKey: MOBILE_MONEY_SECRETS
      remoteRef:
        key: djassa/mobile_money/secret
    - secretKey: CELERY_BROKER_URL
      remoteRef:
        key: djassa/celery/broker_url
