apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hossouko-app-secrets
  namespace: hossouko
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: hossouko-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: hossouko/database/url
    - secretKey: HOSSOUKO_SECRET_KEY
      remoteRef:
        key: hossouko/jwt/secret
    - secretKey: MOBILE_MONEY_SECRETS
      remoteRef:
        key: hossouko/mobile_money/secret
    - secretKey: CELERY_BROKER_URL
      remoteRef:
        key: hossouko/celery/broker_url
