apiVersion: v1
kind: ServiceAccount
metadata:
  name: fidelia-api-sa
  namespace: fidelia

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fidelia-api-role
  namespace: fidelia
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fidelia-api-rolebinding
  namespace: fidelia
subjects:
  - kind: ServiceAccount
    name: fidelia-api-sa
roleRef:
  kind: Role
  name: fidelia-api-role
  apiGroup: rbac.authorization.k8s.io
