apiVersion: v1
kind: Service
metadata:
  name: djassa-api
  namespace: djassa
  labels:
    app: djassa-api
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: djassa-api
