apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hossouko-ingress
  namespace: hossouko
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
    - host: api.hossouko.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hossouko-api
                port:
                  number: 80
  tls:
    - hosts:
        - api.hossouko.example.com
      secretName: hossouko-tls
