apiVersion: v1
kind: ServiceAccount
metadata:
  name: fidelia-sa
  namespace: fidelia

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: fidelia
  name: fidelia-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fidelia-rolebinding
  namespace: fidelia
subjects:
  - kind: ServiceAccount
    name: fidelia-sa
    namespace: fidelia
roleRef:
  kind: Role
  name: fidelia-role
  apiGroup: rbac.authorization.k8s.io
