apiVersion: v1
kind: Service
metadata:
  name: fidelia-api
  namespace: fidelia
spec:
  selector:
    app: fidelia-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
